NumPy Practice Notebook

In [3]:
import numpy as np

In [ ]:
# 1. Array Creation
# 1. 1D array with numbers from 0 to 9
arr1 = np.arange(10)
print(arr1)

# 2. 2D array of shape (3, 3) filled with zeros
arr2 = np.zeros((3, 3))
print(arr2)

# 3. 2D array of shape (2, 4) filled with ones
arr3 = np.ones((2, 4))
print( arr3)

# 4. 3x3 identity matrix
arr4 = np.eye(3)
print( arr4)


[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 2. Array Inspection
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Print shape
print(arr.shape)

# Print data type
print(arr.dtype)

# Print number of dimensions
print(arr.ndim)

# Print total number of elements
print(arr.size)


(2, 3)
int64
2
6


In [ ]:
# 3. Indexing and Slicing
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# 1. Slice the first two rows
first_two_rows = arr[:2, :]
print(first_two_rows)

# 2. Get the last column
last_column = arr[:, -1]
print(last_column)

# 3. Extract the element in the second row and third column
element_2nd_row_3rd_col = arr[1, 2]
print( element_2nd_row_3rd_col)

# 4. Reverse the rows
reversed_rows = arr[::-1, :]
print( reversed_rows)


[[10 20 30]
 [40 50 60]]
[30 60 90]
60
[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [ ]:
# 4. More Slicing Practice
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# 1.  all even numbers
even_numbers = arr[arr % 2 == 0]
print( even_numbers)

# 2. the second and third rows
second_third_rows = arr[1:3, :]
print(second_third_rows)

# 3.  the last two columns
last_two_columns = arr[:, -2:]
print( last_two_columns)

# 4.  the middle 2x2 block (rows 1-2 and columns 1-2)
middle_2x2 = arr[1:3, 1:3]
print( middle_2x2)


[ 2  4  6  8 10 12 14 16]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[ 6  7]
 [10 11]]


In [ ]:
# Arithmetic Operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 1. Add two arrays element-wise
added = arr1 + arr2
print( added)

# 2. Multiply two arrays element-wise
multiplied = arr1 * arr2
print(multiplied) 

# 3. Raise all elements of arr1 to the power of 2
squared = arr1 ** 2
print( squared)


[5 7 9]
[ 4 10 18]
[1 4 9]


In [ ]:
#6. Broadcasting
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

# 1. Add a 1D array to each row of a 2D array
add_row = A + B
print( add_row)

# 2. Multiply each row of a 2D array by a 1D array
multiply_row = A * B
print( multiply_row)

# 3. Subtract a scalar from each element in an array
subtract_scalar = A - 5
print( subtract_scalar)

# 4. Add a column vector to each column of a matrix
add_column = A + C
print( add_column)


[[11 22 33]
 [14 25 36]]
[[ 10  40  90]
 [ 40 100 180]]
[[-4 -3 -2]
 [-1  0  1]]
[[2 3 4]
 [6 7 8]]


In [ ]:
# 7. More Broadcasting Practice
A = np.arange(12).reshape(3, 4)      
B = np.array([100, 200, 300, 400])   
C = np.array([[2], [3], [4]])        

# 1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
add_rowwise = A + B
print(add_rowwise)

# 2. Multiply a (3,1) column array to a (1,4) row array
multiply_outer = C * B.reshape(1, 4)   
print( multiply_outer)
print( multiply_outer.shape)

# 3. Add a scalar to the entire array
add_scalar = A + 10
print( add_scalar)


[[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]
[[ 200  400  600  800]
 [ 300  600  900 1200]
 [ 400  800 1200 1600]]
(3, 4)
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [ ]:
# 8. Reshaping and Flattening
arr = np.arange(12) 

# 1. Reshape to a 3x4 matrix
reshaped_arr = arr.reshape(3, 4)
print( reshaped_arr)

# 2. Flatten back to 1D array
flattened_arr = reshaped_arr.flatten()
print( flattened_arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# 9. Stacking and Splitting
# Two (2,2) arrays
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

# Stack vertically (shape becomes (4,2))
v_stack = np.vstack((a1, a2))
print( v_stack)

# Stack horizontally (shape becomes (2,4))
h_stack = np.hstack((a1, a2))
print( h_stack)

# Reshape a (4,4) array into (2,8)
arr = np.arange(16).reshape(4, 4)
reshaped = arr.reshape(2, 8)
print( reshaped)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[15 20 25 30]
[[ 5 -1 15]
 [-1 25 -1]]


In [19]:
# 10. Boolean Masking

arr = np.array([[5, 10, 15], [20, 25, 30]])

# Select all elements > 10
greater_than_10 = arr[arr > 10]
print( greater_than_10)

# Replace all even numbers with -1
arr[arr % 2 == 0] = -1
print( arr)

[15 20 25 30]
[[ 5 -1 15]
 [-1 25 -1]]


In [ ]:
#11. Aggregation
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
total_sum = np.sum(arr)
print( total_sum)

# Mean of each column
mean_columns = np.mean(arr, axis=0)
print( mean_columns)

# Max value in each row
max_rows = np.max(arr, axis=1)
print( max_rows)

# Standard deviation of the array
std_dev = np.std(arr)
print( std_dev)


21
[2.5 3.5 4.5]
[3 6]
1.707825127659933


In [ ]:
#12. Dot Product and Matrix Multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Multiply using dot product
result = np.dot(A, B)

print( result)


[[19 22]
 [43 50]]


In [ ]:
#13. Random Numbers
# 1. Generate a 2x3 array of random numbers between 0 and 1
random_array = np.random.rand(2, 3)
print( random_array)

# 2. Generate 10 random integers between 50 and 100 (inclusive of 50, exclusive of 100)
random_integers = np.random.randint(50, 100, size=10)
print( random_integers)


[[0.43753365 0.32848677 0.86557971]
 [0.33897854 0.26456348 0.37380462]]
[60 57 89 65 61 74 74 59 80 56]


In [ ]:
#14. Linear Algebra
# Define a square matrix
A = np.array([[1, 2],
              [3, 4]])

# 1. Find the rank of a matrix
rank = np.linalg.matrix_rank(A)
print( rank)

# 2. Compute the inverse of a matrix
inverse = np.linalg.inv(A)
print( inverse)

# 3. Compute the determinant of a matrix
determinant = np.linalg.det(A)
print( determinant)


2
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
